# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/sm8550-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter rtwo,$(TARGET_DEVICE)),)

endif
